---
title: "Ragu's resume"
author: "Ragu"
date: "`r Sys.Date()`"

params:
  pdf_mode:
    value: true

output:
  pagedown::html_resume:
    self_contained: true
    css: custom_resume.css
---

Aside
================================================================================




Contact Info {#contact}
--------------------------------------------------------------------------------

- <li class="small-text"><i class="fa fa-envelope"></i> ragu.manjegowda@gmail.com</li>
- <li class="small-text"><i class="fa fa-globe"></i> <a href="https://raghavendramanjegowda.com/">raghavendramanjegowda.com</a></li>
- <i class="fa fa-linkedin"></i> [ragumanjegowda](https://www.linkedin.com/in/ragumanjegowda/)
- <i class="fa fa-github"></i> [ragu-manjegowda](https://github.com/ragu-manjegowda)
- <i class="fa fa-phone"></i> +1-315-925-9043


Interests & Skills {#skills}
--------------------------------------------------------------------------------

<div style="font-size: 0.85em; line-height: 1.6; margin-top: 0.2in;">
  <ul>
    <li style="margin-bottom: 0.15in; text-align: justify;"> <h4 style="text-align: left; margin-bottom: 0;">Areas of Interest:</h4> Operating System, LLMs, Embedded System, Distributed Systems</li>
    <li style="margin-bottom: 0.15in; text-align: justify;"> <h4 style="text-align: left; margin-bottom: 0;">Tools and Frameworks:</h4> Gained familiarity with variety of them over the years, to name a few: Docker, GDB, Git, Gerrit, Linux, Valgrind, Wireshark, Makefile, CMake, Bazel, RTOS, Jenkins, ArgoCD, K8s, Grafana</li>
    <li style="margin-bottom: 0.15in; text-align: justify;"> <h4 style="text-align: left; margin-bottom: 0;">Programming Languages:</h4> C++, C, Python, Rust, Lua</li>
  </ul>
</div>


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

Raghavendra (Ragu) Manjegowda {#title}
--------------------------------------------------------------------------------

Experienced Embedded Systems and System Software developer with strong
background in Operating Systems and Computer Architecture.


Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Senior Staff Engineer / Engineering Manager III

Nvidia Corporation

Santa Clara, CA

Present - Sept 2018

- Implement efficient data consumption model for Artificial Intelligence 
in cloud, data ingestion infra for recorded data that can be seek/replay/indexed 
used for analytics/debugging/training.
- Implement training and inference pipelines for some of the driving scenarios.
- Optimize and improve performance of the some of the existing training workflows.
- Architect and Implemented workflows for HIL (Hardware in the Loop) and SIL 
(software in the loop) simulation setups for training and inference.
- Worked closely with in-car platform teams and algorithm teams to have robust 
re-playability/reproduce-ability and fault tolerance system for simulation.
- Architect and Lead LLM based simulation for autonomous driving (NRE based 
scenario reconstruction, reactive agent support, radar reprojection) along with 
ability to component replay.
- Converted some of the golang backend code to python for building toolchain.


### Senior Embedded Software Engineer

Samsung Semiconductor

San Jose, CA

Sept 2018 - Sept 2016

- Implement robust and efficient sensor interfaces (LiDAR, RADAR, GPS, IMU, 
CAN, USS) as a middleware component, using various protocols (TCP/UDP, CAN, UART).
- Architect stable and consistent data interfaces for downstream consumers 
like Perception, Localization, Calibration.
- Implement faster and efficient data consumption for both driving and 
recording scenarios.


### Intern, Embedded Software and Internet of Things (R&D)

Hitachi America, Ltd.

Santa Clara, CA

Sept 2016 - January 2016

- Research on localization of sensors in IoT devices to develop solutions 
for next generation of intelligent machines that talk to each other in a 
reliable and secure manner.
- Developed prototypes to demonstrate the research work using various 
sensors and hardware platforms (Raspberry Pi, Arduino) and variety of communication 
protocols (BLE, WiFi, TCP, UDP, Zigbee, CoAP, MQTT)


### Intern, Embedded Software Development

ICM Controls

Syracuse, NY

Dec 2015 - Aug 2015

- Create embedded software and drivers for HVAC devices using Renesas Controller 
in C programming language.
- Verify driver following structured test plan; debug and demonstrate 
firmware on sample boards.
- Create and implement test cases for the software.


### Embedded Software Development Engineer

L&T IES

Bangalore, India

Mar 2014 - Aug 2011

- Software development of calibrating device for Peripheral capillary 
Oxygen Saturation detector (Atmel Controller, C programming language).
- Embedded software development for peripherals of various bio-medical 
devices which include LCD, EEPROM, ADC with the interfaces like SPI, I2C, UART
and GPIO.


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Syracuse University

Master’s Degree, Computer Engineering

Syracuse, NY

2016 - 2014


### Visvesvaraya Technological University

Bachelor’s Degree, Electronics and Communications Engineering

Bangalore, India

2011 - 2007


Projects {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

Some of the hobby projects I have worked on. Please feel free to find more on GitHub.

### Vivitsa 

An Operating system written from Scratch - Written in C 

N/A 

2018 - 2017 

- Unix like Operating system with minimal kernel targeted to run on x86.
- Implemented interrupt handling, paging, heap, virtual file system 
support and multitasking. 
- CI using travis CI guarded with unit tests.
- Build and test environment are dockerized along with scripts to automate, 
easy to try out without installing anything except docker

::: aside
<i class="fa fa-globe"></i> [Project Website](https://raghavendramanjegowda.com/vivitsa/)
:::


### Text Finder 

Grep like command line tool for searching text in files and folders 
recursively - Written in Rust 

N/A 

2021 - 2020 

- Find all files in a directory sub tree with text that matches a specified 
regular expression.
- Find all files that have specified extensions (patterns).
- List all directories and their files in same directory sub tree
- Implemented with dependency inversion principle.
- CI with GitHub actions guarded with unit tests for every function, 
check for formatting and warnings.  
- Build and test environment are dockerized for this project as well. 

::: aside
<i class="fa fa-globe"></i> [Project Website](https://raghavendramanjegowda.com/text-finder/)
:::
